// Este archivo fue generado automáticamente
// No editar a mano. Ejecuta `node generarImageMap.js` para regenerar.

export const imageMap: Record<string, any> = {
  "ISIA/ADRIAN_NICOLAS/AdrianNicolas.jpeg": require('./ISIA/ADRIAN_NICOLAS/AdrianNicolas.jpeg'),
  "ISIA/ALEJANDRO_DEL_PIERO/Alejandro.jpeg": require('./ISIA/ALEJANDRO_DEL_PIERO/Alejandro.jpeg'),
  "ISIA/ANGEL_ONCOY/angel.jpeg": require('./ISIA/ANGEL_ONCOY/angel.jpeg'),
  "ISIA/ANTHONY_ALYNZON/Anthony.jpg": require('./ISIA/ANTHONY_ALYNZON/Anthony.jpg'),
  "ISIA/ARMANDO_JAVIER/armando.png": require('./ISIA/ARMANDO_JAVIER/armando.png'),
  "ISIA/BALTODANO_KARLITA/karlita.jpg": require('./ISIA/BALTODANO_KARLITA/karlita.jpg'),
  "ISIA/BENSON_JOSE_DANIEL/Jose.jpeg": require('./ISIA/BENSON_JOSE_DANIEL/Jose.jpeg'),
  "ISIA/BRYAN_ARTURO/marin.jpg": require('./ISIA/BRYAN_ARTURO/marin.jpg'),
  "ISIA/CARLOS_URIEL/carlos.jpeg": require('./ISIA/CARLOS_URIEL/carlos.jpeg'),
  "ISIA/CHARLIE_MORALES/charli.jpg": require('./ISIA/CHARLIE_MORALES/charli.jpg'),
  "ISIA/DAVID_MAURICIO/luis.jpg": require('./ISIA/DAVID_MAURICIO/luis.jpg'),
  "ISIA/DIEGO_ALONSO/villajulca.jpg": require('./ISIA/DIEGO_ALONSO/villajulca.jpg'),
  "ISIA/FABRICIO_ALEXANDER/alexandder.jpg": require('./ISIA/FABRICIO_ALEXANDER/alexandder.jpg'),
  "ISIA/FERNANDO_MANUEL/Benites.jpg": require('./ISIA/FERNANDO_MANUEL/Benites.jpg'),
  "ISIA/HECTOR_FABRIZZIO/fabrizzio.jpeg": require('./ISIA/HECTOR_FABRIZZIO/fabrizzio.jpeg'),
  "ISIA/JAIME_RAFAEL/Jaime.jpeg": require('./ISIA/JAIME_RAFAEL/Jaime.jpeg'),
  "ISIA/JEFFRY_ALONSO/jeffry.jpg": require('./ISIA/JEFFRY_ALONSO/jeffry.jpg'),
  "ISIA/JHONNATAN_GERARDO/jhonatan.jpg": require('./ISIA/JHONNATAN_GERARDO/jhonatan.jpg'),
  "ISIA/JOE_ALEXIS_MANUEL/Joe.jpeg": require('./ISIA/JOE_ALEXIS_MANUEL/Joe.jpeg'),
  "ISIA/JOHAN_FABRIZIO/johan.jpg": require('./ISIA/JOHAN_FABRIZIO/johan.jpg'),
  "ISIA/JOHN_STEVE/John.jpeg": require('./ISIA/JOHN_STEVE/John.jpeg'),
  "ISIA/JOSE_MIGUEL/1asdasd.jpeg": require('./ISIA/JOSE_MIGUEL/1asdasd.jpeg'),
  "ISIA/JOSE_MIGUEL/ffqewgfrwe.jpg": require('./ISIA/JOSE_MIGUEL/ffqewgfrwe.jpg'),
  "ISIA/JOSE_MIGUEL/Jose.jpg": require('./ISIA/JOSE_MIGUEL/Jose.jpg'),
  "ISIA/JOSE_MIGUEL/rgwgrgweg.jpeg": require('./ISIA/JOSE_MIGUEL/rgwgrgweg.jpeg'),
  "ISIA/JOSE_MIGUEL/WhatsApp Image 2025-05-26 at 6.48.53 PM.jpeg": require('./ISIA/JOSE_MIGUEL/WhatsApp Image 2025-05-26 at 6.48.53 PM.jpeg'),
  "ISIA/JOSE_MIGUEL/WhatsApp Image 2025-05-26 at 6.58.45 PM.jpeg": require('./ISIA/JOSE_MIGUEL/WhatsApp Image 2025-05-26 at 6.58.45 PM.jpeg'),
  "ISIA/JUAN_DIEGO/JuanD.jpg": require('./ISIA/JUAN_DIEGO/JuanD.jpg'),
  "ISIA/JUAN_SMITH/Juan.jpeg": require('./ISIA/JUAN_SMITH/Juan.jpeg'),
  "ISIA/KEVIN_AUGUSTO/KEVIN.jpeg": require('./ISIA/KEVIN_AUGUSTO/KEVIN.jpeg'),
  "ISIA/LUIS_BENJAMIN/drive.jpg": require('./ISIA/LUIS_BENJAMIN/drive.jpg'),
  "ISIA/LUIS_DAVID/Luis.jpg": require('./ISIA/LUIS_DAVID/Luis.jpg'),
  "ISIA/RIDER_PIERRELUIGGI/Pierreluiggi.jpg": require('./ISIA/RIDER_PIERRELUIGGI/Pierreluiggi.jpg'),
  "ISIA/STHEFANO_GABRIEL/sthefano.jpeg": require('./ISIA/STHEFANO_GABRIEL/sthefano.jpeg'),
  "ISIA/SUAREZ_SALAZAR_DRAKO/fdsfsd.jpg": require('./ISIA/SUAREZ_SALAZAR_DRAKO/fdsfsd.jpg'),
  "ISIA/SUAREZ_SALAZAR_DRAKO/ldjsndkjshfds.jpg": require('./ISIA/SUAREZ_SALAZAR_DRAKO/ldjsndkjshfds.jpg'),
  "ISIA/SUAREZ_SALAZAR_DRAKO/SUAREZDRAKO.jpeg": require('./ISIA/SUAREZ_SALAZAR_DRAKO/SUAREZDRAKO.jpeg'),
  "ISIA/SUAREZ_SALAZAR_DRAKO/WhatsApp Image 2025-05-26 at 7.03.43 PM.jpeg": require('./ISIA/SUAREZ_SALAZAR_DRAKO/WhatsApp Image 2025-05-26 at 7.03.43 PM.jpeg'),
  "ISIA/VICTOR_ANDRE/imagen1.jpg": require('./ISIA/VICTOR_ANDRE/imagen1.jpg'),
};
